### PR TITLE
Add LUT maker for ITS1,2,3

### PR DESCRIPTION
**Pull request by njacazio**
@preghenella we need to validate the material, but this is what I tried so far

### CODE REVIEW

**Review by preghenella — CHANGES_REQUESTED** [review]
please, modify the names of the functions
`fatInit_default` --> `fatInit_itsx`
`lutWrite_default`--> `lutWrite_itsx`

I believe you can also remove all the commented lines

**Comment by njacazio** [comment]
Indeed, I cleaned the code and renamed the functions.

**Comment by preghenella** [comment]
ok, when you are ready convert it from draft to real

**Comment by njacazio** [comment]
@preghenella ready for merge, now in ITS3 I added the carbon foam which was missing before

**Pull request merged**
