### PR TITLE
Multiple additions + forward parameterisation + mvl addons 

### PR DESCRIPTION
**Pull request by preghenella**

### CODE REVIEW

**Comment by preghenella** [comment]
@njacazio please have a look.
@marcovanleeuwen I merged your development from your `fwdpara` branch locally, fixed some conflicts that originated from parallel development and this should be how it goes into the `DelphesO2` repo. thanks

**Comment by preghenella** [comment]
I actually notice that is does not work, there was a piece I missed.
will fix it, sorry, coming back soon

**Comment by preghenella** [comment]
@njacazio 
a new way to defined the efficiency is encoded in the LUT in the `eff2` member.
a method has been added to the `TrackSmearer` to decide which efficiency to be used `setWhatEfficiency`.
by default we use the old efficiency definition, but this might change

**Comment by njacazio** [comment]
Ciao @preghenella very large amount of work. I'm fine with the changes!

**Comment by preghenella** [comment]
ok thanks @njacazio 
I merge it. hopefully we will manage to test it ;)

**Pull request merged**
