### PR TITLE
Support for dN/deta dependence of the LUTs

### PR DESCRIPTION
**Pull request by preghenella**
This PR is WIP

### CODE REVIEW

**Comment by preghenella** [comment]
ciao @njacazio 
can you please help me with this PR?
to check if something is wrong / missing and so on and so forth.

surely something is missing at the level of the TrackSmearer, which I will take care of right away

thanks

**Comment by njacazio** [comment]
Ciao @preghenella, outstanding! I will have a look

**Comment by preghenella** [comment]
@njacazio the Nch can now be set via method of TrackSmearer

**Comment by njacazio** [comment]
Ciao @preghenella it looks ok for me!

**Review by njacazio — APPROVED** [review]

**Pull request merged**
